### PR TITLE
Better Includes

### PR DESCRIPTION
**Pull request by bokay**
Hi @dlitvakb,

This PR will do two things:
- Return the includes in the API response
- Give the responsability of managing the include resolution to another module

This has two advantages: 
- the developer has the choice of resolving or not the includes
- the resolution will do all the available resolution possible, but not recursively. Calling a second time `IncludeResolver.resolve_entry` will go a bit deeper and so on.

What's your opinion ?

### CODE REVIEW

**Comment by dlitvakb** [comment]
Hey @bokay,

I like the separation of the include resolution into it's own module, though I don't like the change on the interface.

I'd prefer having the option to resolve or not includes as an optional parameter to the entries/entry methods defaulting to true, and keep the same external API.

We can work on having it work with lazy evaluation on the future, now that it is modularized.

**Comment by bokay** [comment]
Those two last commit should do the trick 👍

**Comment by bokay** [comment]
On another topic, when do think we should start using versions on the library ?

**Comment by dlitvakb** [comment]
Hey @bokay,

Thanks for the contribution! Looks great!

I'll do a release of a `0.1.0` version now after merging

Cheers

**Comment by dlitvakb** [comment]
Hey @bokay,

Release done and added a Changelog

Do you want me to add an AUTHORS file and also add you there?

**Comment by bokay** [comment]
As you wish 😉

**Pull request merged**
