### PR TITLE
Add inch

### LINKED ISSUE #32: Add inch for docs coverage
Might be a good idea to add [inch](https://inch-ci.org/).

- [ ] bonus credit for adding a badge

### PR DESCRIPTION
**Pull request by asaaki**
This PR fixes #32.

-----

Initial local report:

```
# Proper documentation present
┃
┃ [B] → Contentful.Query.skip/2 (lib/contentful/query.ex:97)
┃ [B] → Contentful.Query.limit/2 (lib/contentful/query.ex:72)
┃ [B] → Contentful.Delivery.url/1 (lib/contentful_delivery/delivery.ex:164)
┃ [B] → Contentful.Delivery.url/2 (lib/contentful_delivery/delivery.ex:189)
┃ [B] → Contentful.Query.stream/4 (lib/contentful/query.ex:274)
┃ [B] → Contentful.Query.include/2 (lib/contentful/query.ex:36)
┃ [B] → Contentful.Stream.stream/4 (lib/contentful/stream.ex:8)
┃ [B] → Contentful.Delivery.config/2 (lib/contentful_delivery/delivery.ex:368)
┃ [B] → Contentful.Query.fetch_all/4 (lib/contentful/query.ex:154)
┃ [B] → Contentful.Query.fetch_one/5 (lib/contentful/query.ex:203)

# Undocumented
┃
┃ [U] → Contentful.Asset.t/0 (lib/contentful/asset.ex:12)
┃ [U] → Contentful.Entry.t/0 (lib/contentful/entry.ex:13)
┃ [U] → Contentful.Space.t/0 (lib/contentful/space.ex:9)
┃ [U] → Contentful.Locale.t/0 (lib/contentful/locale.ex:12)
┃ [U] → Contentful.SysData.t/0 (lib/contentful/sys_data.ex:10)
┃ [U] → Contentful.ContentType.t/0 (lib/contentful/content_type.ex:18)
┃ [U] → Contentful.Asset.Fields.t/0 (lib/contentful/asset/fields.ex:14)
┃ [U] → Contentful.Asset.__struct__/0 (lib/contentful/asset.ex:10)
┃ [U] → Contentful.Asset.__struct__/1 (lib/contentful/asset.ex:10)
┃ [U] → Contentful.Entry.__struct__/0 (lib/contentful/entry.ex:11)

You might want to look at these files:

┃  lib/contentful_delivery/delivery.ex
┃  lib/contentful/query.ex
┃  lib/contentful/content_type.ex
┃  lib/contentful/sys_data.ex
┃  lib/contentful/space.ex

Please report incorrect results: https://github.com/rrrene/inch_ex/issues

Grade distribution (undocumented, C, B, A): █ ▁ ▆ ▇

Only considering priority objects: ↑ ↗ →  (use `--help` for options).
```

### CODE REVIEW

**Comment by floriank** [comment]
Thanks!

Seems like tons of documentation work still to do :)

**Comment by asaaki** [comment]
Btw I'm not so sure about the InchCI service.
For my personal project the service didn't record any report anymore (always "?"):
https://inch-ci.org/github/asaaki/cmark.ex/builds
And therefore also the badge doesn't update.
For this here not even a badge is generated.

So I would say we just include a normal "mix inch" step, which has purely informational character. (Fun fact: the task also seems a bit broken, `--help` doesn't work for me.)

**Comment by floriank** [comment]
Is there a way to run the `mix inch` task separately? We don't really need this for every version combination of OTP and elixir, after all.

**Comment by asaaki** [comment]
We could create a second job or even a workflow just for that.

**Comment by asaaki** [comment]
So a new job section works.
I also moved the coveralls part into it, since it also needs to run only once per push.

**Pull request merged**
