### PR TITLE
Configurable endpoint

### PR DESCRIPTION
**Pull request by zaeemarshad**
- Move functions to Contentful.Functions module
- Create new modules for delivery and preview with endpoints as module attributes

TODO: Write tests for preview.

### CODE REVIEW

**Comment by dlitvakb** [comment]
Hey @zaeemarshad,

This looks really good,

Please let me know when it's done and I can test it and merge it.

Cheers

**Comment by zaeemarshad** [comment]
@dlitvakb thanks. This is ready to go as there are no changes needed at the moment. I'd appreciate if you can merge it now. I will be contributing to the test code later.

**Comment by zaeemarshad** [comment]
@dlitvakb any update on the merge?

**Comment by dlitvakb** [comment]
Hey @zaeemarshad,

I'm currently working on adding more verbose errors to all main SDKs I maintain, as soon as I finish that, which should be between today and tomorrow. I have some free time to take a look into this.

Cheers

**Comment by asaaki** [comment]
@floriank do we want to close the PR as they are relying on an old version of the code?

**Comment by floriank** [comment]
Closing, as this will be superseded by #31

**Pull request closed without merging**
